server:
  max-http-header-size: 40000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /

mybatis:
  type-aliases-package: tech.portfolo.portfolo.*.*.vo
  mapper-locations: /mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  url: http://localhost:8080

